# Write your MySQL query statement below


SELECT PERSON_NAME
FROM 
    (SELECT PERSON_NAME, 
           SUM(WEIGHT) OVER (ORDER BY TURN) AS TOTAL_WEIGHT,
           TURN
    FROM QUEUE
) AS TEMP
WHERE TOTAL_WEIGHT <=1000
ORDER BY TURN DESC
LIMIT 1