# Write your MySQL query statement below

SELECT P.PRODUCT_ID, IFNULL(ROUND(SUM(U.UNITS * P.PRICE) / SUM(U.UNITS),2), 0) AS AVERAGE_PRICE
FROM PRICES AS P
LEFT JOIN UNITSSOLD AS U
ON P.PRODUCT_ID = U.PRODUCT_ID
AND U.PURCHASE_DATE BETWEEN P.START_DATE AND P.END_DATE
GROUP BY P.PRODUCT_ID
