# Write your MySQL query statement below

(SELECT NAME AS RESULTS
FROM USERS INNER JOIN MovieRating USING(USER_ID) 
GROUP BY USER_ID
ORDER BY COUNT(RATING)DESC,NAME
LIMIT 1)

UNION ALL

(SELECT TITLE AS RESULTS
FROM MOVIES INNER JOIN MovieRating USING(MOVIE_ID)
WHERE MONTH(CREATED_AT) = '02' AND YEAR(CREATED_AT) = '2020'
GROUP BY MOVIE_ID
ORDER BY AVG(RATING) DESC, TITLE
LIMIT 1)





