# Write your MySQL query statement below
SELECT S.USER_ID, IFNULL(ROUND(SUM(ACTION= 'CONFIRMED')/COUNT(*),2), 0.00) AS CONFIRMATION_RATE
FROM SIGNUPS AS S
LEFT JOIN CONFIRMATIONS AS C
ON S.USER_ID = C.USER_ID
GROUP BY S.USER_ID